version: '2'
services:
  app-postgresql:
    image: postgres:11.2
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=app
      - POSTGRES_DB=app
    ports:
      - 5432:5432
# volumes:
#   database-data:
